theme: jekyll-theme-cayman
markdown: kramdown

# Site
title: Naziya Tasnim
description: Software Developer | Digital Artist | Dreamer
show_links: true
links:
    linkedin: https://www.linkedin.com/in/naziya-tasnim
    github: https://github.com/nazy00
    instagram: https://www.instagram.com/hostile_user/

# Projects
show_projects: true
projects:
    cybardev/dbsys-webapp: Full-stack Flask + MySQL Web App for Database Systems course
    cybardev/Noctrun: 2D side-scrolling endless runner featuring the ghosts of Bengal
    cybardev/pictionary: Fun game for kids to learn the Mi'kmaq language
